

all:
	g++ perception-udp.cpp -lrealsense2 -o perception-udp
	# g++ -std=c++11 -I/usr/local/include/opencv2 -L/usr/bin -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_videoio -lrealsense2 -o object_tracking tracking.cpp
	# g++ tracking.cpp -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_videoio -lrealsense2 -o object_tracking 

